services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    volumes:
      # Persist WhatsApp sessions between restarts
      - ./.wwebjs_auth:/app/.wwebjs_auth
      # Mount your groups.csv file if you want to use it
      - ./groups.csv:/app/groups.csv:ro
      # Mount logs directory
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    restart: unless-stopped
    # Ensure container has enough resources
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
